### ISSUE TITLE
Server.py error

### ISSUE THREAD

**Issue by alirazaman** [AcidCaos/socialemperors#34]
any time i run server.py command in cmd.exe even after installing jsonpatch, flask, and install requests using pip, I get this when I type server.py
E:\socialemperors-main>server.py
 [+] Loading basics...
 [+] Loading game config...
Traceback (most recent call last):
  File "E:\socialemperors-main\server.py", line 13, in <module>
    from get_game_config import get_game_config, patch_game_config
  File "E:\socialemperors-main\get_game_config.py", line 3, in <module>
    import jsonpatch
ModuleNotFoundError: No module named 'jsonpatch'

**Comment by Nerroth** [comment]
You haven't installed the requirements correctly and your Python installation does not have the required modules to run the project. Since this isn't an issue I will be closing this.
